name: Make Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag (e.g., v0.1.0)'
        required: true
        default: 'v0.1.0'
      title:
        description: 'Release title'
        required: true
        default: 'Zaxor Vane Filters'

# allow release & tag writes
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Ensure artifact exists for upload (works even if repo doesn't commit dist/)
      - name: Ensure dist/filters.json exists
        run: |
          mkdir -p dist
          if [ ! -f dist/filters.json ]; then
            cat > dist/filters.json <<'EOF'
            {
              "focus": ["military", "cyber", "blackout", "blockade", "sanctions", "anomaly"],
              "avoid": ["celebrity gossip", "sports drama"],
              "whitelist_sources": ["Reuters","DW","BBC","AP","Al Jazeera","ZeroHedge","Grayzone","MintPress"],
              "boost": ["breaking","leak","satellite","troop movement","energy grid","currency swap"]
            }
            EOF
          fi
          ls -lah dist/

      # Create or update the release (auto-creates the tag if missing)
      - name: Create/Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          name: ${{ inputs.title }}
          artifacts: "dist/filters.json"
          artifactErrorsFailBuild: true
          allowUpdates: true
          replacesArtifacts: true
